# Generated by Django 4.2 on 2023-05-07 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_profile_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user",
        ),
    ]
